services:

  minimal-notebook:
    image: quay.io/jupyter/minimal-notebook:2024-09-02
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work
    tty: true

  postgres:
    container_name: postgres_db
    # Official Postgres image from DockerHub (we use the last version)
    image: 'pgvector/pgvector:pg16'
    # limit the memory and cpu usage
    # mem_limit: 512m
    # mem_reservation: 128M
    # cpus: 0.5
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    # Note: You are free to change your computer's port,
    # but take into consideration that it will change the way
    # you are connecting to your database.
    ports:
      - 5435:5435
    command: "-p 5435"
    environment:
      - POSTGRES_DB=postgres # The PostgreSQL default database (automatically created at first launch)
      - POSTGRES_USER=postgres # The PostgreSQL user (useful to connect to the database)
      - POSTGRES_PASSWORD=postgres # The PostgreSQL password (useful to connect to the database)
      - "POSTGRES_HOST_AUTH_METHOD=trust"
